#pragma once

#include "handle.h"
#include <string>

namespace clickhouse_odbc {

// Utility functions
std::string WideToUtf8(const SQLWCHAR *wide, SQLSMALLINT len);
std::string WideToUtf8(const std::wstring &wide);
std::wstring Utf8ToWide(const std::string &utf8);

SQLRETURN CopyStringToBuffer(const std::string &src, SQLCHAR *target, SQLSMALLINT buffer_length,
                             SQLSMALLINT *string_length);
SQLRETURN CopyStringToBufferW(const std::string &src, SQLWCHAR *target, SQLSMALLINT buffer_length,
                              SQLSMALLINT *string_length);

// Parse connection string (key=value;key=value;...)
std::unordered_map<std::string, std::string> ParseConnectionString(const std::string &conn_str);

// String helpers
std::string ToUpper(const std::string &s);
std::string Trim(const std::string &s);

// Resolve SQL_C_DEFAULT to actual C type based on SQL parameter type
SQLSMALLINT ResolveCDefaultType(SQLSMALLINT sql_type);

// Parameter binding: extract parameter value as string from BoundParameter
std::string ExtractParameterValue(const BoundParameter &param);

// Escape a string value for ClickHouse SQL (single quotes escaped)
std::string EscapeSqlString(const std::string &value);

// Substitute '?' placeholders in query with bound parameter values
// Returns the substituted query string, or empty string on error (with error_msg set)
std::string SubstituteParameters(const std::string &query,
                                 const std::unordered_map<SQLUSMALLINT, BoundParameter> &params,
                                 std::string &error_msg);

// ODBC escape sequence processing
// Converts ODBC escape sequences to ClickHouse-compatible SQL:
//   {fn UCASE(x)}  -> upper(x)
//   {d 'yyyy-mm-dd'}  -> 'yyyy-mm-dd'
//   {t 'hh:mm:ss'}    -> 'hh:mm:ss'
//   {ts 'yyyy-mm-dd hh:mm:ss'}  -> 'yyyy-mm-dd hh:mm:ss'
//   {oj ...}  -> ... (pass through outer join)
//   {escape 'x'}  -> (processed for LIKE)
std::string ProcessOdbcEscapeSequences(const std::string &sql);

// MS Access SQL conversion: SELECT TOP N → LIMIT N
// Converts SELECT TOP N syntax generated by Access to ClickHouse's LIMIT N.
// Example: SELECT TOP 10 * FROM table → SELECT * FROM table LIMIT 10
//          SELECT DISTINCT TOP 1 col FROM t WHERE ... → SELECT DISTINCT col FROM t WHERE ... LIMIT 1
std::string ConvertTopToLimit(const std::string &sql);

} // namespace clickhouse_odbc
